### PR TITLE
Preserve depth of bmp while creating raw

### PR DESCRIPTION
**Pull request by heartlandzf**

### CODE REVIEW

**Comment by EliTeDev-44** [comment]
Hi, thank you for your great contribution !!!

I do not know if this is the right jar, but I'm trying to extract the Mili_chaohu.res file with the res2img.py script but I can not get it to work.

=======================================
C:\Users\Yo\Cocina Android\Amazfit Bip\tools-master\tools-master>res2img.py -u -i Mili_chaohu.res
Traceback (most recent call last):
  File "C:\Users\Yo\Cocina Android\Amazfit Bip\tools-master\tools-master\res2img.py", line 268, in <module>
    fileHeader, version, dummy1, dummmy2 = struct.unpack('5sbHL', fileContent[0:16])
struct.error: unpack requires a string argument of length 12

C:\Users\Yo\Cocina Android\Amazfit Bip\tools-master\tools-master>python res2img.py -u -i Mili_chaohu.res
  File "res2img.py", line 51
    print "no argument"
                      ^
SyntaxError: Missing parentheses in call to 'print'

C:\Users\Yo\Cocina Android\Amazfit Bip\tools-master\tools-master>

========================================

You have a good day.

**Comment by heartlandzf** [comment]
No, I haven't made a great contribution (only bug correction)

And no, better you ask to the author 

Anyway I use the script without issues of this kind ..

**Comment by EliTeDev-44** [comment]
Ok thanks

**Comment by dpeddi** [comment]
please check you are using the correct python versione (2.7.x)

**Pull request merged**
