### PR TITLE
Czech language added, bugfixing

### PR DESCRIPTION
**Pull request by winni159**
I created small tools to merge translated strings a check translations

### CODE REVIEW

**Comment by dpeddi** [comment]
please could you document a little in README.md these new 2 utilities?

Regards

**Comment by dpeddi** [comment]
ps: I've added you as a member, so you should be able to self push your changes!

**Comment by winni159** [comment]
Hi! I updated readme file... I'm not able to push changes to your git. Did you set the rights correctly?

**Comment by dpeddi** [comment]
now you should be able to push.. sorry

**Pull request merged**
